baseURL = "https://imymirror.github.io/"
languageCode = "en-us"
title = "Imymirror"
theme = "yinyang"
DefaultContentLanguage = "cn"
publishDir = "docs"

[author]
  name = "Imymirror"
  homepage = "https://imymirror.github.io/"

[languages]
  # [languages.en]
  #   contentDir = "content/en"
  #   languageName = "English"
  #   weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2

[permalinks]
    post = "/blog/:title/"

[params]
headTitle = "Imymirror"
description = "I am your mirror."
disqus = "imymirror-andy" # disqus account name
extraHead = ''
mainSections = ["posts"]
lazyImage = true

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "about"
link = "/about"


[[params.socials]]
name = "Github"
link = "https://github.com/Imymirror"

